server: 
   port: 9000
management:
   endpoints:
       web:
           exposure:
               include: health,jolokia
spring:
   kafka:
     consumer:
        bootstrap-servers: h2908727.stratoserver.net:9092
        group-id: group_id
        auto-offset-reset: earliest
        key-deserializer: org.javacream.training.kafka.spring.log.LogMessageKeySerde
        value-deserializer: org.javacream.training.kafka.spring.log.LogMessageValueSerde
     producer:
        bootstrap-servers: h2908727.stratoserver.net:9092
        key-serializer: org.javacream.training.kafka.spring.log.LogMessageKeySerde
        value-serializer: org.javacream.training.kafka.spring.log.LogMessageValueSerde
