version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: javacream/kafka_broker
    ports:
      - "9092:9092"
      - "9192:9192"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: h2908727.stratoserver.net 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: -javaagent:./jolokia-agent.jar=port=9192,host=kafka1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: javacream/kafka_broker
    ports:
      - "9093:9092"
      - "9193:9192"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: h2908727.stratoserver.net 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: -javaagent:./jolokia-agent.jar=port=9192,host=kafka2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: javacream/kafka_broker
    ports:
     - "9094:9092"
     - "9194:9192"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: h2908727.stratoserver.net 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: -javaagent:./jolokia-agent.jar=port=9192,host=kafka3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
